### ISSUE TITLE
create tab nav

### ISSUE THREAD

**Issue by Giggles0369** [MadnessLabs/MadnessLifeOLD#4]

**Comment by zachgreeley101** [comment]
![nav bar redesign](https://cloud.githubusercontent.com/assets/7705196/14039031/963d3192-f225-11e5-9dbb-e0b04dbff85b.jpg)

This is my plan for the new nav bar with tabs. Very simple design for now. I'm a very visual person when it comes to design. I have marked up a nav bar design with the appropriate tabs. What do you think? I created this in photoshop and put a file on the drive if you wanted to edit it.

**Comment by popcorn245** [comment]
Looking good man. Here is the link to the Ionic docs for how to make tabs. 

http://ionicframework.com/docs/api/directive/ionTabs/

You will want to put these in your app.jade file. NOTE: you may have to restart the build process (Ctrl + C 2 times when in terminal, then gulp again)

**Comment by zachgreeley101** [comment]
Ok so i have been really messing around with ionic tabs. I have a better understanding on how the whole framework works. But for some reason when i try to make changes to madness-life app. Ether everything disappears or gulp crashes. So we need to go over that tonight. I'm most likely editing the code in the wrong spot.
